version: 2

registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.KEYMASTER_TOKEN}}

updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    registries: "*"
    schedule:
      interval: 'weekly'
      day: "friday"
    commit-message:
      prefix: "[GitHub Actions] "
    labels:
      - "github actions"
      - "dependencies"
    groups:
      github-actions:
        patterns:
          - "*"