name: Code Styling

on:
  workflow_call:
    inputs:
      php_version:
        description: 'PHP version to be used.'
        required: false
        type: string
        default: '8.3'
      message:
        description: 'Commit message.'
        type: string
        default: Styling
      test_mode:
        description: 'Test mode.'
        required: false
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  pint:
    if: "!contains(github.event.head_commit.message, 'wip')"
    name: Pint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          tools: composer:v2, laravel/pint
          extensions: json, dom, curl, libxml, mbstring
          coverage: none

      - name: Run Pint
        run: pint ${{ inputs.test_mode && '--test' || '' }}

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ inputs.message }}
